### ISSUE TITLE
Load older comments on summary page

### ISSUE THREAD

**Issue by AustenLamacraft** [tripos-education/maths-tripos-questions#48]
It would be natural to load older comments when you get to the bottom of the latest comments. I think Giscus does this with `useSWRInfinite` from [SWR](https://swr.vercel.app/), so it *should* be relatively straightforward

**Comment by AustenLamacraft** [comment]
Infinite scroll is now implemented

**Comment by thenewtonium** [comment]
This is really neat!
Might make sense to get rid of ( / reword) the *For older comments, see [GitHub discussions](https://github.com/tripos-education/maths-tripos-questions/discussions).* at the bottom of the homepage now then 😅
