### ISSUE TITLE
[Typo] Missing closing bracket in 2020 Paper 3, Section I, 10C  (QIC)

### ISSUE THREAD

**Issue by thenewtonium** [tripos-education/maths-tripos-questions#89]
Part (iii) is missing a closing bracket around the $\dagger$.

**Comment by AustenLamacraft** [comment]
If you'd like to try editing the markdown directly in GH I think it will create a pull request that I can then handle. Easiest is probably to go to https://github.com/tripos-education/maths-tripos-questions/find/master and find the markdown in `/src/part-ii/`. You can see the file name from the URL e.g. this one is `2020-126.md`.

**Comment by thenewtonium** [comment]
Ah nice yeah, I forgot pull requests were a thing...

(Might be an idea to mention this more explicitly in FAQ for those of us less au-fait with GH... well I guess I can l do this in a pull request lol)

**Comment by thenewtonium** [comment]
I see you've fixed this typo in your fixing of missing eqn labels. Time to close this issue...
