### ISSUE TITLE
[bug/typo] Missing equation labels

### ISSUE THREAD

**Issue by thenewtonium** [tripos-education/maths-tripos-questions#92]
The pdf to latex conversion process has removed the labels from all equations, which are often important for the question to make sense.

**Comment by AustenLamacraft** [comment]
Thanks. Yes, I had seen a couple of these. Can you give some examples? It's possible it's there in the markdown, but needs some help.

**Comment by thenewtonium** [comment]
I was reminded of this from looking at QIC questions, e.g. [2020 P3 10C](part-ii/2020-126/) and [2020 P2 10C](part-ii/2020-125/) both reference labelled equations. I've definitely seen others that do this in the past but none specifically come to mind unfortunately.

I think the problem is that the labels use the `\tag*` which is only available in the $LaTeX$ `equation` environment, so basically *can't* be added in via LaTeX anymore. 

I guess they can be added back in by just putting e.g. `$~~~~(\dagger)$` or something at the end of the equation; doesn't *quite* preserve the original formatting, but gets across the information. Maybe there is another solution to this but all the ones I can think of involve somehow either
- using HTML in the .md files (I assume it's supported since it works for comments? but it can mess with the LaTeX rendering so might not work), or
- making a plugin for the markdown renderer (effort).

**Comment by AustenLamacraft** [comment]
OK, it's quite easy in fact. I just fixed a bunch of missing daggers by adding `\tag{†}` (the unicode symbol, not `\dagger`) in the math block environment of the equation. Same goes for `\tag{‡}` (double dagger). I think there are still a bunch of missing stars to be fixed with `\tag{*}` but that's a start.

**Comment by thenewtonium** [comment]
oh interesting 🤔

**Comment by AustenLamacraft** [comment]
That's because (I've just discovered) Netlify builds a deploy preview for every pull request, which is a nice feature but takes a while for a big site with Eleventy (and several PRs)
